<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Tools_2_0</RootNamespace>
    <AssemblyName>Tools_2.0</AssemblyName>
    <Platforms>AnyCPU</Platforms>
    <Version>2.4.0</Version>
    <AssemblyVersion>2.4.0.0</AssemblyVersion>
    <FileVersion>2.4.0.0</FileVersion>
    <InformationalVersion>2.4.0</InformationalVersion>
    <Product>Tools</Product>
    <AssemblyTitle>Tools</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tools.csproj" />
  </ItemGroup>
</Project>
